apiVersion: functions.stackit.cloud/v1alpha
kind: Revision
metadata:
  created: 2026-05-15T17:46:45Z
  annotations:
    cli.functions.stackit.cloud/local-memory-limit-mb: '512'
spec:
  image: rg.fr-par.scw.cloud/bouke/solar-panel-checker:latest@sha256:fc38103a33e298be58dc446d0b22d003b4abfaa57f284073889a268b79f9cf6c
  limits:
    plan: f3
    concurrency: 0
