apiVersion: functions.stackit.cloud/v1alpha
kind: Revision
metadata:
  created: 2026-05-15T17:46:45Z
  annotations:
    cli.functions.stackit.cloud/local-memory-limit-mb: '512'
spec:
  image: rg.fr-par.scw.cloud/bouke/solar-panel-checker:latest@sha256:edd1b0219ecf8225ffc9fe58c5bc1adb3ae0abbafe78b9eed939f697d9b6e0c0
  limits:
    plan: f3
    concurrency: 0
